name: Blog CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14   

    - name: newman reporter
      run: sudo npm install -g newman-reporter-htmlextra            
      
    - name: Install Dependencies
      run: sudo npm install

    - name: Run npm start
      run: npm start  

    - name: Aguardar a aplicação startar
      run: sleep 30      
      
    - name: Step 1 Check version
      run: |
        newman --version
        node --version            
    
    - name: run newman reporter
      run: newman run ./blog-ci.json -e ./blog-env.json       
